import { BloonColor, BloonLayer, DamageType, DifficultyPreset, GameDifficulty, Point, TowerConfig, Wave } from './types';

export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 600;


export const DIFFICULTY_PRESETS: Record<GameDifficulty, DifficultyPreset> = {
  [GameDifficulty.Easy]: {
    id: GameDifficulty.Easy,
    label: 'Easy',
    startingMoney: 750,
    startingLives: 200,
    roundBonusBase: 120,
    roundBonusScale: 1,
    sellbackRate: 0.75,
  },
  [GameDifficulty.Medium]: {
    id: GameDifficulty.Medium,
    label: 'Medium',
    startingMoney: 650,
    startingLives: 100,
    roundBonusBase: 100,
    roundBonusScale: 1,
    sellbackRate: 0.7,
  },
  [GameDifficulty.Hard]: {
    id: GameDifficulty.Hard,
    label: 'Hard',
    startingMoney: 500,
    startingLives: 75,
    roundBonusBase: 80,
    roundBonusScale: 0.9,
    sellbackRate: 0.65,
  },
};

export const PATH_NODES: Point[] = [
  { x: 0, y: 100 },
  { x: 200, y: 100 },
  { x: 200, y: 400 },
  { x: 400, y: 400 },
  { x: 400, y: 200 },
  { x: 600, y: 200 },
  { x: 600, y: 500 },
  { x: 800, y: 500 },
];

export const BLOON_STATS: Record<BloonColor, BloonLayer> = {
  [BloonColor.Red]: { color: BloonColor.Red, health: 1, speed: 90, children: [], childCount: 0, immunities: [], r: 15, money: 1, leakLives: 1 },
  [BloonColor.Blue]: { color: BloonColor.Blue, health: 1, speed: 126, children: [BloonColor.Red], childCount: 1, immunities: [], r: 16, money: 1, leakLives: 1 },
  [BloonColor.Green]: { color: BloonColor.Green, health: 1, speed: 162, children: [BloonColor.Blue], childCount: 1, immunities: [], r: 17, money: 1, leakLives: 1 },
  [BloonColor.Yellow]: { color: BloonColor.Yellow, health: 1, speed: 288, children: [BloonColor.Green], childCount: 1, immunities: [], r: 18, money: 1, leakLives: 1 },
  [BloonColor.Pink]: { color: BloonColor.Pink, health: 1, speed: 312, children: [BloonColor.Yellow], childCount: 1, immunities: [], r: 15, money: 1, leakLives: 1 },
  [BloonColor.Black]: { color: BloonColor.Black, health: 1, speed: 162, children: [BloonColor.Pink], childCount: 2, immunities: [DamageType.Explosive], r: 14, money: 1, leakLives: 2 },
  [BloonColor.White]: { color: BloonColor.White, health: 1, speed: 180, children: [BloonColor.Pink], childCount: 2, immunities: [DamageType.Freeze], r: 14, money: 1, leakLives: 2 },
  [BloonColor.Lead]: { color: BloonColor.Lead, health: 1, speed: 72, children: [BloonColor.Black], childCount: 2, immunities: [DamageType.Sharp], r: 16, money: 1, leakLives: 3 },
  [BloonColor.Zebra]: { color: BloonColor.Zebra, health: 1, speed: 216, children: [BloonColor.Black, BloonColor.White], childCount: 1, immunities: [], r: 15, money: 1, leakLives: 3 },
  [BloonColor.Rainbow]: { color: BloonColor.Rainbow, health: 1, speed: 228, children: [BloonColor.Zebra], childCount: 2, immunities: [], r: 16, money: 1, leakLives: 4 },
  [BloonColor.Ceramic]: { color: BloonColor.Ceramic, health: 10, speed: 180, children: [BloonColor.Rainbow], childCount: 2, immunities: [], r: 18, money: 2, leakLives: 10 },
  [BloonColor.MOAB]: { color: BloonColor.MOAB, health: 200, speed: 60, children: [BloonColor.Ceramic], childCount: 4, immunities: [], r: 35, money: 100, leakLives: 100 },
};

export const TOWERS: Record<string, TowerConfig> = {
  DART: {
    id: 'DART',
    name: 'Dart Monkey',
    cost: 200,
    range: 150,
    damage: 1,
    cooldown: 40,
    pierce: 2,
    projectileSpeed: 15,
    damageType: DamageType.Sharp,
    color: '#8B5A2B',
    upgrades: [
      { name: 'Sharp Shots', description: '+2 pierce', cost: 140, effect: { pierce: 2 } },
      { name: 'Very Quick Shots', description: 'Attack 50% faster', cost: 200, effect: { cooldownMult: 0.5 } },
    ],
  },
  TACK: {
    id: 'TACK',
    name: 'Tack Shooter',
    cost: 400,
    range: 100,
    damage: 1,
    cooldown: 50,
    pierce: 1,
    projectileSpeed: 10,
    damageType: DamageType.Sharp,
    color: '#FF69B4',
    upgrades: [
      { name: 'Fast Tacks', description: 'Faster shots', cost: 210, effect: { cooldownMult: 0.7 } },
      { name: 'Extra Range Tacks', description: '+30 range', cost: 300, effect: { range: 30 } },
    ],
  },
  CANNON: {
    id: 'CANNON',
    name: 'Bomb Shooter',
    cost: 600,
    range: 180,
    damage: 2,
    cooldown: 80,
    pierce: 10,
    projectileSpeed: 10,
    damageType: DamageType.Explosive,
    color: '#333333',
    upgrades: [
      { name: 'Bigger Bombs', description: '+1 damage', cost: 400, effect: { damage: 1 } },
      { name: 'Missile Launcher', description: 'Faster missiles', cost: 500, effect: { projectileSpeed: 5 } },
    ],
  },
  SNIPER: {
    id: 'SNIPER',
    name: 'Sniper Monkey',
    cost: 450, // Buffed cost
    range: 2000,
    damage: 2, // High damage
    cooldown: 100,
    pierce: 1,
    projectileSpeed: 0, // 0 = Hitscan
    damageType: DamageType.Sharp,
    color: '#556B2F',
    upgrades: [
      { name: 'Full Metal Jacket', description: '+2 damage', cost: 350, effect: { damage: 2 } },
      { name: 'Faster Firing', description: 'Fire faster', cost: 400, effect: { cooldownMult: 0.7 } },
    ],
  },
  WIZARD: {
    id: 'WIZARD',
    name: 'Wizard Monkey',
    cost: 400,
    range: 160,
    damage: 1,
    cooldown: 45,
    pierce: 3,
    projectileSpeed: 12,
    damageType: DamageType.Magic,
    color: '#4B0082',
    upgrades: [
      { name: 'Intense Magic', description: '+2 pierce', cost: 300, effect: { pierce: 2 } },
      { name: 'Fireball', description: 'Huge explosion dmg', cost: 550, effect: { damage: 2 } },
    ],
  },
  SUPER: {
    id: 'SUPER',
    name: 'Super Monkey',
    cost: 2500,
    range: 250,
    damage: 1,
    cooldown: 3, // Insanely fast
    pierce: 1,
    projectileSpeed: 20,
    damageType: DamageType.Sharp,
    color: '#FFFF00',
    upgrades: [
      { name: 'Laser Blasts', description: '+1 dmg, magic type', cost: 2500, effect: { damage: 1 } },
      { name: 'Epic Range', description: '+100 range', cost: 1500, effect: { range: 100 } },
    ],
  },
  FARM: {
    id: 'FARM',
    name: 'Banana Farm',
    cost: 1000,
    range: 0,
    damage: 0,
    cooldown: 360,
    pierce: 0,
    projectileSpeed: 0,
    damageType: DamageType.Sharp,
    color: '#facc15',
    income: 80,
    upgrades: [
      { name: 'More Bananas', description: '+60 cash per harvest', cost: 700, effect: { income: 60 } },
      { name: 'Banana Plantation', description: '+120 cash per harvest', cost: 1400, effect: { income: 120 } },
    ],
  },
};

export const WAVES: Wave[] = [
  [{ type: BloonColor.Red, count: 20, spacing: 1.0 }],
  [{ type: BloonColor.Red, count: 35, spacing: 0.8 }],
  [{ type: BloonColor.Red, count: 25, spacing: 0.5 }, { type: BloonColor.Blue, count: 5, spacing: 0.5 }],
  [{ type: BloonColor.Red, count: 35, spacing: 0.4 }, { type: BloonColor.Blue, count: 18, spacing: 0.4 }],
  [{ type: BloonColor.Red, count: 5, spacing: 0.5 }, { type: BloonColor.Blue, count: 27, spacing: 0.5 }],
  [{ type: BloonColor.Red, count: 15, spacing: 0.6 }, { type: BloonColor.Blue, count: 15, spacing: 0.6 }, { type: BloonColor.Green, count: 4, spacing: 0.6 }],
  [{ type: BloonColor.Red, count: 20, spacing: 0.4 }, { type: BloonColor.Blue, count: 20, spacing: 0.4 }, { type: BloonColor.Green, count: 5, spacing: 0.4 }],
  [{ type: BloonColor.Red, count: 10, spacing: 0.4 }, { type: BloonColor.Blue, count: 20, spacing: 0.4 }, { type: BloonColor.Green, count: 14, spacing: 0.4 }],
  [{ type: BloonColor.Blue, count: 30, spacing: 0.2 }],
  [{ type: BloonColor.Blue, count: 102, spacing: 0.1 }],
  [{ type: BloonColor.Red, count: 10, spacing: 0.2 }, { type: BloonColor.Blue, count: 10, spacing: 0.2 }, { type: BloonColor.Green, count: 12, spacing: 0.2 }, { type: BloonColor.Yellow, count: 3, spacing: 0.5 }],
  [{ type: BloonColor.Blue, count: 15, spacing: 0.2 }, { type: BloonColor.Green, count: 10, spacing: 0.2 }, { type: BloonColor.Yellow, count: 5, spacing: 0.5 }],
  [{ type: BloonColor.Blue, count: 50, spacing: 0.1 }, { type: BloonColor.Green, count: 23, spacing: 0.1 }],
  [{ type: BloonColor.Red, count: 49, spacing: 0.15 }, { type: BloonColor.Blue, count: 15, spacing: 0.15 }, { type: BloonColor.Green, count: 10, spacing: 0.15 }, { type: BloonColor.Yellow, count: 9, spacing: 0.3 }],
  [{ type: BloonColor.Red, count: 20, spacing: 0.1 }, { type: BloonColor.Blue, count: 15, spacing: 0.1 }, { type: BloonColor.Green, count: 12, spacing: 0.1 }, { type: BloonColor.Yellow, count: 10, spacing: 0.2 }, { type: BloonColor.Pink, count: 5, spacing: 0.2 }],
  [{ type: BloonColor.Green, count: 40, spacing: 0.2 }, { type: BloonColor.Yellow, count: 8, spacing: 0.3 }],
  [{ type: BloonColor.Yellow, count: 12, spacing: 0.1 }],
  [{ type: BloonColor.Green, count: 80, spacing: 0.1 }],
  [{ type: BloonColor.Green, count: 10, spacing: 0.1 }, { type: BloonColor.Yellow, count: 10, spacing: 0.1 }, { type: BloonColor.Pink, count: 7, spacing: 0.2 }],
  [{ type: BloonColor.Black, count: 6, spacing: 1.0 }],
  [{ type: BloonColor.Black, count: 10, spacing: 0.8 }, { type: BloonColor.White, count: 8, spacing: 0.8 }],
  [{ type: BloonColor.Yellow, count: 30, spacing: 0.08 }, { type: BloonColor.Pink, count: 18, spacing: 0.1 }],
  [{ type: BloonColor.Green, count: 35, spacing: 0.08 }, { type: BloonColor.Yellow, count: 25, spacing: 0.08 }, { type: BloonColor.Pink, count: 12, spacing: 0.1 }],
  [{ type: BloonColor.White, count: 18, spacing: 0.12 }, { type: BloonColor.Black, count: 18, spacing: 0.12 }],
  [{ type: BloonColor.Pink, count: 40, spacing: 0.06 }],
  [{ type: BloonColor.Black, count: 24, spacing: 0.1 }, { type: BloonColor.White, count: 24, spacing: 0.1 }, { type: BloonColor.Pink, count: 20, spacing: 0.12 }],
  [{ type: BloonColor.Yellow, count: 30, spacing: 0.08 }, { type: BloonColor.Pink, count: 35, spacing: 0.08 }, { type: BloonColor.Black, count: 12, spacing: 0.2 }],
  [{ type: BloonColor.White, count: 20, spacing: 0.08 }, { type: BloonColor.Black, count: 20, spacing: 0.08 }, { type: BloonColor.Pink, count: 30, spacing: 0.08 }],
  [{ type: BloonColor.Black, count: 35, spacing: 0.07 }, { type: BloonColor.White, count: 35, spacing: 0.07 }],
  [{ type: BloonColor.Pink, count: 50, spacing: 0.05 }, { type: BloonColor.Black, count: 25, spacing: 0.08 }, { type: BloonColor.White, count: 25, spacing: 0.08 }],
  [{ type: BloonColor.Lead, count: 14, spacing: 0.3 }, { type: BloonColor.Black, count: 20, spacing: 0.1 }],
  [{ type: BloonColor.Zebra, count: 20, spacing: 0.18 }, { type: BloonColor.Pink, count: 25, spacing: 0.08 }, { type: BloonColor.Rainbow, count: 10, spacing: 0.2 }],
  [{ type: BloonColor.Lead, count: 24, spacing: 0.18 }, { type: BloonColor.Zebra, count: 16, spacing: 0.16 }, { type: BloonColor.Rainbow, count: 12, spacing: 0.12 }],
  [{ type: BloonColor.Zebra, count: 36, spacing: 0.1 }, { type: BloonColor.Black, count: 36, spacing: 0.08 }, { type: BloonColor.Ceramic, count: 8, spacing: 0.25 }],
  [{ type: BloonColor.Lead, count: 20, spacing: 0.12 }, { type: BloonColor.Zebra, count: 40, spacing: 0.08 }, { type: BloonColor.Pink, count: 40, spacing: 0.06 }, { type: BloonColor.Ceramic, count: 12, spacing: 0.2 }],
  [{ type: BloonColor.MOAB, count: 1, spacing: 1.0 }],
];
